// GENERATED by scripts/goal-staging/generate-im1-goal-payload.mjs.
// Reviewed production candidate only; loading this file performs no write.
const IM1_GOAL_PAYLOAD_METADATA = {
  "schemaVersion": 1,
  "expectedRowCount": 164,
  "reviewSha256": "c68f78c5ad6ffcbba439d21147063b3d65670c467fe929e767995b8b5c727ed2",
  "previewSnapshotLastUpdated": "2026-08-16T03:50:25.682Z",
  "payloadSha256": "b996e724bd07ef9cc2a032bde0aec14a42a1b57d2d41311e13e05cfa0ced1ca2",
  "confirmationPhrase": "IMPORT-IM1-PARITY-B996E724BD07EF9C-CONFIRMED"
};
const IM1_GOAL_ROWS = [
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U1",
    "LessonID": "AMP-IM1-U1-I01",
    "LessonTitle": "Meet & Greet",
    "KeyOutcome": "I can make connections with classmates and think about math collaboratively. | I can describe connections between the structure of a visual pattern and expressions that model it.",
    "PlannedDays": 1,
    "NonParitySHA256": "52c55fd8ae997b42755d3e6663447e43c9b4b496528aa5294d46b5c6ebb3d73b"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U1",
    "LessonID": "AMP-IM1-U1-I02",
    "LessonTitle": "M1.1 Pre-Unit Check",
    "KeyOutcome": "I can show what I already understand about ideas that will support this unit.",
    "PlannedDays": 1,
    "NonParitySHA256": "61e0b563985a9b3e9aad9b3b795a51536cdf7a291df29d8d49e28a346bc41563"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U1",
    "LessonID": "AMP-IM1-U1-I03",
    "LessonTitle": "Patterns Found in Nature",
    "KeyOutcome": "I can describe patterns seen in different representations of the Fibonacci sequence.",
    "PlannedDays": 1,
    "NonParitySHA256": "431eb1998899b8aeb21ba8fd037071a6708442fbc82f9129bb45f2621179cb8d"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U1",
    "LessonID": "AMP-IM1-U1-I04",
    "LessonTitle": "Visual Patterns",
    "KeyOutcome": "I can use tables and images to make predictions about a pattern. | I can describe patterns in a table and in an image.",
    "PlannedDays": 1,
    "NonParitySHA256": "fa74e47439771b2bcdbe32612e59521d152351e67b2b5b2ec56f7cda47f06b32"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U1",
    "LessonID": "AMP-IM1-U1-I05",
    "LessonTitle": "Sequence Carnival",
    "KeyOutcome": "I can determine a missing term in a sequence. | I can justify whether a sequence has a constant difference or a constant ratio.",
    "PlannedDays": 1,
    "NonParitySHA256": "2dded4d56c8d3ebda6979849cba7953f4d3f0376952f0d9c8885f4a759cc5261"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U1",
    "LessonID": "AMP-IM1-U1-I06",
    "LessonTitle": "Recursion Machine",
    "KeyOutcome": "I can define a sequence recursively to meet certain requirements.",
    "PlannedDays": 1,
    "NonParitySHA256": "56b29d2e75ed532163b078c026d3cef0357f39c99eb7a204723f7644ad0786a4"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U1",
    "LessonID": "AMP-IM1-U1-I07",
    "LessonTitle": "See the Sequence",
    "KeyOutcome": "I can determine whether a sequence is arithmetic, geometric, or neither. | I can make connections between tables, graphs, and recursive definitions of sequences. | I can compare arithmetic and geometric sequences using tables and graphs.",
    "PlannedDays": 1,
    "NonParitySHA256": "69f5aa34ab2560d9eded86a408cbe8343ab53e983766fb9f03add8dd6d5ac917"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U1",
    "LessonID": "AMP-IM1-U1-I08",
    "LessonTitle": "Paper Patterns",
    "KeyOutcome": "I can represent situations with tables, graphs, and expressions. | I can interpret the meanings of parts of an expression in context.",
    "PlannedDays": 1,
    "NonParitySHA256": "9186e356eb671dcb7f4abaccdb2c01c652bf4d4cd4ec978b76c886707aabf164"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U1",
    "LessonID": "AMP-IM1-U1-I09",
    "LessonTitle": "More Visual Patterns",
    "KeyOutcome": "I can write an explicit expression for an arithmetic sequence or a geometric sequence. | I can explain that different explicit expressions can represent the same sequence. | I can interpret the meanings of parts of an expression in context.",
    "PlannedDays": 1,
    "NonParitySHA256": "74a5d11f3ca3737b5203eab1afa56848dd757aa9526caa42eb98ffc0973b6c9a"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U1",
    "LessonID": "AMP-IM1-U1-I10",
    "LessonTitle": "Tree-Mendous Models",
    "KeyOutcome": "I can model situations using recursive definitions and explicit expressions to help solve real-world problems. | I can use math to make sense of issues in a community. | I can describe how to revise a model to incorporate new information.",
    "PlannedDays": 1,
    "NonParitySHA256": "f72311f2566b1e4a0a124d6c27dfb3d47df9a675e3143f9ce34b3823cc317e73"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U1",
    "LessonID": "AMP-IM1-U1-I11",
    "LessonTitle": "M1.1 Practice Day",
    "KeyOutcome": "I can apply the concepts, skills, and strategies developed in this unit.",
    "PlannedDays": 1,
    "NonParitySHA256": "fbb2616629f5a055c971a4713868d521638dda2d97eb67737fb79983691813a4"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U1",
    "LessonID": "AMP-IM1-U1-I12",
    "LessonTitle": "M1.1 Performance Task",
    "KeyOutcome": "I can demonstrate proficiency with the concepts and skills addressed in this unit.",
    "PlannedDays": 1,
    "NonParitySHA256": "ed7f7c7a3157be13b17a7b9dbb3355370b1538ce62a2fe230c75e2a0074c15db"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U1",
    "LessonID": "AMP-IM1-U1-I13",
    "LessonTitle": "Unit Synthesis and Reflection",
    "KeyOutcome": "I can be purposeful, strategic, and goal-oriented about my learning. | I can connect different ideas from this unit and across units. | I can revisit ideas from this unit, revise my thinking, and reflect on my growth.",
    "PlannedDays": 1,
    "NonParitySHA256": "8cc95b0a340270e94b4e88b35482d03a8c0642767892356a9c5dffab9effdb40"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U2",
    "LessonID": "AMP-IM1-U2-I01",
    "LessonTitle": "M1.2 Pre-Unit Check",
    "KeyOutcome": "I can show what I already understand about ideas that will support this unit.",
    "PlannedDays": 1,
    "NonParitySHA256": "54ab09030af8997b14417153ff223f224b5ae286166b9597f8821859a53ee3c7"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U2",
    "LessonID": "AMP-IM1-U2-I02",
    "LessonTitle": "Planning for Homecoming",
    "KeyOutcome": "I can use conditions from real-world contexts to maximize value. | I can determine which choices meet given conditions in a real-world context. | I can explain a method for maximizing value while meeting the conditions in a real-world context.",
    "PlannedDays": 1,
    "NonParitySHA256": "b510c42a661cf47d1b29a49889721ec823182a6392b18a71adb5cb615f393baf"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U2",
    "LessonID": "AMP-IM1-U2-I03",
    "LessonTitle": "Working Backwards",
    "KeyOutcome": "I can use inverse operations to solve an equation. | I can describe strategies for solving multi-step equations.",
    "PlannedDays": 1,
    "NonParitySHA256": "2d576ab21db333eac5681e3a293129d8fe6601c9a4ea19b80557f3eb0a3978a7"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U2",
    "LessonID": "AMP-IM1-U2-I04",
    "LessonTitle": "Solving Strategies",
    "KeyOutcome": "I can solve one-variable linear equations. | I can analyze others' reasoning when solving linear equations. | I can justify that each step in solving a linear equation creates an equivalent equation with the same solution.",
    "PlannedDays": 1,
    "NonParitySHA256": "58e8f59fa5c1fcd72cf96fd3da4c7ccefc20e7a4679c2c835a7f0299fe48a1cf"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U2",
    "LessonID": "AMP-IM1-U2-I05",
    "LessonTitle": "Same Position",
    "KeyOutcome": "I can explain that dividing by a variable does not always create equivalent equations. | I can justify whether a one-variable equation has one solution, no solution, or infinitely many solutions.",
    "PlannedDays": 1,
    "NonParitySHA256": "c3db0a5b9ffc95267e161912db00d7cb781c305d3a87d8602d3e8d35f7d386a3"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U2",
    "LessonID": "AMP-IM1-U2-I06",
    "LessonTitle": "Subway Seats",
    "KeyOutcome": "I can identify equivalent forms of linear equations and understand that different forms of a linear equation can be useful for different purposes. | I can represent constraints with two-variable equations and interpret their solutions. | I can interpret different forms of a two-variable linear equation in context.",
    "PlannedDays": 1,
    "NonParitySHA256": "52c0892c2876f3435c89fe7d9700308de1cd720d61e567d032a2e5ca681f1b5e"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U2",
    "LessonID": "AMP-IM1-U2-I07",
    "LessonTitle": "Various Variables",
    "KeyOutcome": "I can rearrange multi-variable equations to highlight a variable of interest. | I can solve multi-variable equations for a variable of interest. | I can explain how solving for a variable is similar to rearranging an equation to isolate a variable of interest.",
    "PlannedDays": 1,
    "NonParitySHA256": "ec9a414ce5f8aa7e9c68457dd5e4b350d4e9cd94bddb13a8c02640fe2d0c18f3"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U2",
    "LessonID": "AMP-IM1-U2-I08",
    "LessonTitle": "Shelley the Snail",
    "KeyOutcome": "I can explain that the graph of a linear equation represents all the pairs of values that are solutions to that equation. | I can solve an equation in standard form for one of its variables and connect the new equation to its graph. | I can discuss how the graph of a linear equation can be written in different but equivalent forms.",
    "PlannedDays": 1,
    "NonParitySHA256": "91c6ff63e0583540d80940ebfc1dc7e2a57635d83d2129080cbe3aa6a6acc349"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U2",
    "LessonID": "AMP-IM1-U2-I09",
    "LessonTitle": "Equations of Lines",
    "KeyOutcome": "I can generalize that a line can be represented by an equation in point-slope form. | I can write the equation of a line in point-slope form. | I can describe the properties of a line when given its equation in point-slope form.",
    "PlannedDays": 1,
    "NonParitySHA256": "ad32eb76f2d861ba3b2d8c05e5fb72de4678f7379ac472cf7dc9114de3853a58"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U2",
    "LessonID": "AMP-IM1-U2-I10",
    "LessonTitle": "Five Representations",
    "KeyOutcome": "I can write two linear equations to represent the same situation: one in standard form and one in slope-intercept form. | I can describe connections between equations, tables, descriptions, and graphs of linear situations.",
    "PlannedDays": 1,
    "NonParitySHA256": "65afb8eff76024881ecccc4c21f846ac29ff57ccb47a6a078e386db0c3c0624b"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U2",
    "LessonID": "AMP-IM1-U2-I11",
    "LessonTitle": "M1.2 Practice Day 1",
    "KeyOutcome": "I can apply the concepts, skills, and strategies developed in Lessons 1–8.",
    "PlannedDays": 1,
    "NonParitySHA256": "e595671b833d7098b57317c07182f42b47b1f1ef29682ed294f67fb3868a9611"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U2",
    "LessonID": "AMP-IM1-U2-I12",
    "LessonTitle": "M1.2 Sub-Unit Quiz",
    "KeyOutcome": "I can demonstrate my understanding of the concepts and skills developed so far in this unit.",
    "PlannedDays": 1,
    "NonParitySHA256": "8d8e9e7dd21cbc46128e6e5b9ba2d6b9ad40ada2cf14f050d31deff23eade2d5"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U2",
    "LessonID": "AMP-IM1-U2-I13",
    "LessonTitle": "Pizza Delivery",
    "KeyOutcome": "I can explain that solutions to an inequality are values that make the inequality true. | I can write one-variable inequalities that represent constraints. | I can describe and interpret solutions to one-variable inequalities in context.",
    "PlannedDays": 1,
    "NonParitySHA256": "297eaa2de3b74b3fb8c9c08eadf340c01673bb3fee124951f8ca292dfdf4903b"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U2",
    "LessonID": "AMP-IM1-U2-I14",
    "LessonTitle": "Graphing Inequalities",
    "KeyOutcome": "I can solve one-variable inequalities by reasoning. | I can graph solutions to a one-variable inequality on a number line. | I can describe how to represent the solutions to a one-variable inequality on a number line.",
    "PlannedDays": 1,
    "NonParitySHA256": "b7b71a398b7df21c87452b425eee70a7ef35eb1cfc5eabfd0eea0585fe087e00"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U2",
    "LessonID": "AMP-IM1-U2-I15",
    "LessonTitle": "Solutions and Sheep",
    "KeyOutcome": "I can solve a one-variable linear inequality by solving its corresponding equation and testing values. | I can describe a strategy for solving and graphing the solutions to an inequality.",
    "PlannedDays": 1,
    "NonParitySHA256": "7894621392017186b02c988d3333f1173263525d1959786fed25520892abfef9"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U2",
    "LessonID": "AMP-IM1-U2-I16",
    "LessonTitle": "Absolute Value Solutions",
    "KeyOutcome": "I can solve one-variable absolute value equations and inequalities. | I can graph solutions to absolute value equations and inequalities on a number line. | I can explain the meaning of absolute value equations and inequalities.",
    "PlannedDays": 1,
    "NonParitySHA256": "f68383c59ea718f1f1075b5e8de8b455c204de99372e7f02c1885412dd32b666"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U2",
    "LessonID": "AMP-IM1-U2-I17",
    "LessonTitle": "All Sorts of Screws",
    "KeyOutcome": "I can create absolute value inequalities to solve problems. | I can solve one-variable absolute value equations and inequalities. | I can explain the meaning of absolute value equations and inequalities, and their solutions in context.",
    "PlannedDays": 1,
    "NonParitySHA256": "7388c5fd4b5fa955f309dc14427067448212c696c47301dd467983ca4dc3ae39"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U2",
    "LessonID": "AMP-IM1-U2-I18",
    "LessonTitle": "Bracelet Budgets",
    "KeyOutcome": "I can explain that the solutions to a two-variable inequality are points that make the inequality true. | I can interpret two-variable inequalities that represent constraints in context.",
    "PlannedDays": 1,
    "NonParitySHA256": "90b6bf114f7aa557d38b923fb1c6dbd0217c3d71e0c9a9347ac17c7230c62de4"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U2",
    "LessonID": "AMP-IM1-U2-I19",
    "LessonTitle": "All of the Solutions",
    "KeyOutcome": "I can explain that the solutions to a two-variable linear inequality are represented on a graph as a half-plane (excluding the boundary in the case of a strict inequality). | I can graph the solutions to a two-variable linear inequality given the graph of its corresponding equation. | I can describe a strategy for graphing the solutions to a two-variable linear inequality.",
    "PlannedDays": 1,
    "NonParitySHA256": "6c5315124e119d1b1bc12527eb453cec20e30dc622fe6efdaaaaa9b157808a8a"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U2",
    "LessonID": "AMP-IM1-U2-I20",
    "LessonTitle": "Charity Concerts",
    "KeyOutcome": "I can graph the solutions to a two-variable linear inequality and interpret its solutions in context. | I can write a two-variable inequality to represent a situation in context. | I can interpret what an inequality and its solutions mean in context.",
    "PlannedDays": 1,
    "NonParitySHA256": "8c7e751bb953287a1e86076b3747bafeb6dbea612104096d5096651c727a5b2d"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U2",
    "LessonID": "AMP-IM1-U2-I21",
    "LessonTitle": "Water Way",
    "KeyOutcome": "I can model real-world constraints and solutions using two-variable linear inequalities. | I can analyze two-variable linear inequalities in order to make sense of an issue in society.",
    "PlannedDays": 1,
    "NonParitySHA256": "59b91a520d8099a1126e39d6d5c2b24274936a771164b3c7a60e99f1347af8ba"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U2",
    "LessonID": "AMP-IM1-U2-I22",
    "LessonTitle": "M1.2 Practice Day 2",
    "KeyOutcome": "I can apply the concepts, skills, and strategies developed in Lessons 1–17.",
    "PlannedDays": 1,
    "NonParitySHA256": "5907a0834376a8f24b212f89b8f7686e47069e87946bc523caab653d09ccb9d6"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U2",
    "LessonID": "AMP-IM1-U2-I23",
    "LessonTitle": "M1.2 Performance Task",
    "KeyOutcome": "I can demonstrate proficiency with the concepts and skills addressed in this unit.",
    "PlannedDays": 1,
    "NonParitySHA256": "3de314c9f3cdcb9fdd4a9d2a81a08634f6b1f70843a8d6b7bb18a27d7bd81e0f"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U2",
    "LessonID": "AMP-IM1-U2-I24",
    "LessonTitle": "Unit Synthesis and Reflection",
    "KeyOutcome": "I can be purposeful, strategic, and goal-oriented about my learning. | I can connect different ideas from this unit and across units. | I can revisit ideas from this unit, revise my thinking, and reflect on my growth.",
    "PlannedDays": 1,
    "NonParitySHA256": "a8f55182917b2121ffa9c759d016a26b11ecdca3c61e83fe37ce2c108e32cb46"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U3",
    "LessonID": "AMP-IM1-U3-I01",
    "LessonTitle": "M1.3 Pre-Unit Check",
    "KeyOutcome": "I can show what I already understand about ideas that will support this unit.",
    "PlannedDays": 1,
    "NonParitySHA256": "52732d3936d6429841199cfed692286ca2cf11cfc5bfa6979b4d635c8815db1b"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U3",
    "LessonID": "AMP-IM1-U3-I02",
    "LessonTitle": "A Community Fundraiser",
    "KeyOutcome": "I can determine how many participants are needed to meet certain fundraising goals within given constraints. | I can explain potential modifications to fundraising earnings and costs to increase profit.",
    "PlannedDays": 1,
    "NonParitySHA256": "5bff0291b3d90a474c5a1495d9489af772053d47d70707372522b6343afba1b2"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U3",
    "LessonID": "AMP-IM1-U3-I03",
    "LessonTitle": "Shape It Up",
    "KeyOutcome": "I can use reasoning to solve shape puzzles to prepare students for solving systems of equations in this unit. | I can explain a strategy for solving shape puzzles to prepare students for solving systems of equations in this unit.",
    "PlannedDays": 1,
    "NonParitySHA256": "c0eee730c8cf1f2949d1c9b29aeac828fe203f0b10bf561d22ca7a86929ed123"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U3",
    "LessonID": "AMP-IM1-U3-I04",
    "LessonTitle": "Eliminating Shapes",
    "KeyOutcome": "I can solve systems of equations by adding or subtracting the equations to eliminate a variable. | I can identify when to use addition or subtraction to eliminate a variable.",
    "PlannedDays": 1,
    "NonParitySHA256": "10001fb22e5ca92df17ac6d1c597822b2b94996537caf7d8cf956f628264ec97"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U3",
    "LessonID": "AMP-IM1-U3-I05",
    "LessonTitle": "Process of Elimination",
    "KeyOutcome": "I can solve a system of equations using an elimination strategy. | I can explain how replacing an equation in a system with one that is equivalent creates a new system that has the same solution.",
    "PlannedDays": 1,
    "NonParitySHA256": "eb289f9d8e1a81bc342d41de83d2bb0c6840afae0ee93041efc168d3ba37b01d"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U3",
    "LessonID": "AMP-IM1-U3-I06",
    "LessonTitle": "Solution by Substitution",
    "KeyOutcome": "I can solve systems of equations using substitution. | I can describe a strategy for solving systems of equations using substitution.",
    "PlannedDays": 1,
    "NonParitySHA256": "9ad8e4ddaa8a9770b44c74c43a5de62c3a684d1d8c0c57c171b6f6b7a6a4a319"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U3",
    "LessonID": "AMP-IM1-U3-I07",
    "LessonTitle": "Lizard Lines",
    "KeyOutcome": "I can solve a system of linear equations using a graph. | I can analyze the structure of a system of equations to justify whether the system has zero, one, or infinitely many solutions.",
    "PlannedDays": 1,
    "NonParitySHA256": "75179dbacbfb5e9aad3473d681310b2965fedb093b5a016f984957581bfce0ba"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U3",
    "LessonID": "AMP-IM1-U3-I08",
    "LessonTitle": "City Development",
    "KeyOutcome": "I can solve systems of equations graphically and symbolically.s. | I can interpret the solution to a system of equations in context.",
    "PlannedDays": 1,
    "NonParitySHA256": "1261afe66fb91ec4560dfa23c44133e7855224545710205dc4d36790aee97d5f"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U3",
    "LessonID": "AMP-IM1-U3-I09",
    "LessonTitle": "Bus Systems",
    "KeyOutcome": "I can represent a situation with a system of equations. | I can solve systems of equations graphically and symbolically. | I can interpret the meaning of a system of equations and its solutions in context in order to make recommendations.",
    "PlannedDays": 1,
    "NonParitySHA256": "ed351dcc1dce475504dbf89725b934429331bf2f17eeb0f4ef3f637aa9f6fe43"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U3",
    "LessonID": "AMP-IM1-U3-I10",
    "LessonTitle": "Electric Line Zapper",
    "KeyOutcome": "I can develop fluency in solving systems of linear equations using substitution and elimination. | I can describe how to look for and make use of structures in equations to choose a solving strategy. | I can explain the connection between a false statement obtained algebraically and no solution to the system.",
    "PlannedDays": 1,
    "NonParitySHA256": "33801abd163ab68874bb1c3fa7b9a05fcc71f9732b32b177add224ca2dd539b1"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U3",
    "LessonID": "AMP-IM1-U3-I11",
    "LessonTitle": "M1.3 Practice Day 1",
    "KeyOutcome": "I can apply the concepts, skills, and strategies developed in Lessons 1–8.",
    "PlannedDays": 1,
    "NonParitySHA256": "679053199ed55102ff5ea2316c25c12256478d84e08ed3b48042afc3bec4a31d"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U3",
    "LessonID": "AMP-IM1-U3-I12",
    "LessonTitle": "Quilts",
    "KeyOutcome": "I can determine if a point is a solution to a system of inequalities using a graph. | I can describe how ordered pairs relate to constraints in a situation.",
    "PlannedDays": 1,
    "NonParitySHA256": "2d58c29c8c39b4d8ba2eabc9c69834b9ac804aedf2843642b78108c03efc014a"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U3",
    "LessonID": "AMP-IM1-U3-I13",
    "LessonTitle": "Seeking Solutions",
    "KeyOutcome": "I can determine the solution region of a system of inequalities given the boundary lines. | I can describe how to determine the solution region of a system of inequalities on a graph.",
    "PlannedDays": 1,
    "NonParitySHA256": "8b246a9bad62d672b0e60a8274207ffc63d39afad05b8254a8f562f2932597ed"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U3",
    "LessonID": "AMP-IM1-U3-I14",
    "LessonTitle": "Boundaries and Shading",
    "KeyOutcome": "I can write a system of inequalities when given a graph. | I can graph the solution region to a system of inequalities. | I can describe a strategy for graphing the solution region to a system of inequalities.",
    "PlannedDays": 1,
    "NonParitySHA256": "1017b846b8b0b67661a0ac8e1a60e443a443c03804815cfe3069bad305c4e38c"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U3",
    "LessonID": "AMP-IM1-U3-I15",
    "LessonTitle": "Community Meals",
    "KeyOutcome": "I can write systems of inequalities to represent constraints in context. | I can interpret the solutions to a system of inequalities in context in order to make decisions.",
    "PlannedDays": 1,
    "NonParitySHA256": "1946a691a1df1549cde824cb05baf7574fb942a26ecc78a0a129d9cebc902319"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U3",
    "LessonID": "AMP-IM1-U3-I16",
    "LessonTitle": "M1.3 Practice Day 2",
    "KeyOutcome": "I can apply the concepts, skills, and strategies developed in Lessons 1–12.",
    "PlannedDays": 1,
    "NonParitySHA256": "212f3cb971c150ad8cf5ee64b76d8540d277dcd4ec3449e047dafb219c534142"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U3",
    "LessonID": "AMP-IM1-U3-I17",
    "LessonTitle": "M1.3 Sub-Unit Quiz",
    "KeyOutcome": "I can demonstrate my understanding of the concepts and skills developed so far in this unit.",
    "PlannedDays": 1,
    "NonParitySHA256": "2c94164b47a66305e9d7ff81712cfaa768c8da299f29a5e9e665bf3c389e0657"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U3",
    "LessonID": "AMP-IM1-U3-I18",
    "LessonTitle": "Parallel Lines on the Coordinate Grid",
    "KeyOutcome": "I can prove algebraically the slope criteria for parallel lines. | I can use the parallel line slope criteria to write equations of lines. | I can explain how translations and the slope formula justify that parallel lines have the same slope.",
    "PlannedDays": 1,
    "NonParitySHA256": "6c0dd3d0f8a3efc2e2099de8e5cdbd122734e3770517bf27257547fa04cbdde7"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U3",
    "LessonID": "AMP-IM1-U3-I19",
    "LessonTitle": "Perpendicular Lines on the Coordinate Grid",
    "KeyOutcome": "I can prove that the slopes of perpendicular lines are opposite reciprocals. | I can use slopes of perpendicular lines to solve problems. | I can justify whether two lines are perpendicular.",
    "PlannedDays": 1,
    "NonParitySHA256": "30cb84a3cdcc1e834d7a97fcd59b22a6ca190c2b3e24f111b83ec55ff73abcd4"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U3",
    "LessonID": "AMP-IM1-U3-I20",
    "LessonTitle": "It's All on the Line",
    "KeyOutcome": "I can write an equation for a line that travels through a given point and is either parallel or perpendicular to a given line. | I can explain why two lines that are perpendicular to the same line must be parallel to each other.",
    "PlannedDays": 1,
    "NonParitySHA256": "8d8689b7a743fae9836afa2d4d262a024cde74c32ce463446109f817d98a0f5a"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U3",
    "LessonID": "AMP-IM1-U3-I21",
    "LessonTitle": "Going the Distance",
    "KeyOutcome": "I can derive the distance formula from the Pythagorean theorem. | I can use the distance formula to find the length of the segment that connects two points. | I can compare the Pythagorean theorem to the distance formula.",
    "PlannedDays": 1,
    "NonParitySHA256": "2326b8b2996e4201f77e4e9662bf31da8ea199e415575fb9fd1c0728dd12049a"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U3",
    "LessonID": "AMP-IM1-U3-I22",
    "LessonTitle": "Restaurant Math",
    "KeyOutcome": "I can use coordinates and the distance formula to compute perimeters and areas of polygons. | I can describe the information needed and the steps for determining the perimeter and area of shapes on a coordinate grid.",
    "PlannedDays": 1,
    "NonParitySHA256": "e5dfbd327a9b4032a33cb55eb485390b7711a4c393e0d67119536284ac885347"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U3",
    "LessonID": "AMP-IM1-U3-I23",
    "LessonTitle": "M1.3 Practice Day 3",
    "KeyOutcome": "I can apply the concepts, skills, and strategies developed in Lessons 1–17.",
    "PlannedDays": 1,
    "NonParitySHA256": "e3dbaff22622b77ac45d6b57e388a3e5e58734961a074af9f6775e6579bb3590"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U3",
    "LessonID": "AMP-IM1-U3-I24",
    "LessonTitle": "M1.3 Performance Task",
    "KeyOutcome": "I can demonstrate proficiency with the concepts and skills addressed in this unit.",
    "PlannedDays": 1,
    "NonParitySHA256": "1953a3e283e3a9eb00af58a73fcdf4cfecf9905ef0ff400fb88462aac90942d6"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U3",
    "LessonID": "AMP-IM1-U3-I25",
    "LessonTitle": "Unit Synthesis and Reflection",
    "KeyOutcome": "I can be purposeful, strategic, and goal-oriented about my learning. | I can connect different ideas from this unit and across units. | I can revisit ideas from this unit, revise my thinking, and reflect on my growth.",
    "PlannedDays": 1,
    "NonParitySHA256": "a7f03837d1eec2f05a73928f4dd9dbdb4cae7e8f49d38d6341dca0acc4f4ca43"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U4",
    "LessonID": "AMP-IM1-U4-I01",
    "LessonTitle": "M1.4 Pre-Unit Check",
    "KeyOutcome": "I can show what I already understand about ideas that will support this unit.",
    "PlannedDays": 1,
    "NonParitySHA256": "8540a9c8ea9c699e8c2df31d73b9e98c6c1b33ebca98a91a2e4bd911560c1aeb"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U4",
    "LessonID": "AMP-IM1-U4-I02",
    "LessonTitle": "School Commutes",
    "KeyOutcome": "I can sketch a graph to match a situation. | I can describe how situations are represented in graphs.",
    "PlannedDays": 1,
    "NonParitySHA256": "78750662e4f99459b9b4ca8863eee7f957da2a58b8b5932fe1338d2bb09281d2"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U4",
    "LessonID": "AMP-IM1-U4-I03",
    "LessonTitle": "Mystery Rule",
    "KeyOutcome": "I can determine whether or not a rule is a function. | I can explain that a function has only one output for every input.",
    "PlannedDays": 1,
    "NonParitySHA256": "4eb9e4b373989eed5e358950cb353dc24325383cdc241f737bd2e9cef0e6509d"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U4",
    "LessonID": "AMP-IM1-U4-I04",
    "LessonTitle": "Pricing Pizzas",
    "KeyOutcome": "I can interpret a statement written in function notation in context.",
    "PlannedDays": 1,
    "NonParitySHA256": "7afbd5db450f518bc90edaf2c1b2aa8b9e8bbe18a08bd707786df70fdd23fe87"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U4",
    "LessonID": "AMP-IM1-U4-I05",
    "LessonTitle": "Toy Factory",
    "KeyOutcome": "I can evaluate functions written in function notation. | I can write equations of functions using function notation. | I can describe equations written in function notation in context.",
    "PlannedDays": 1,
    "NonParitySHA256": "6f18df504ead8b3ed75b81d5719fb8fefb6f8e9b11e7fa10e1b20c90962d5d75"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U4",
    "LessonID": "AMP-IM1-U4-I06",
    "LessonTitle": "Function Carnival",
    "KeyOutcome": "I can sketch a graph of a function to match a situation. | I can describe connections between situations and graphs.",
    "PlannedDays": 1,
    "NonParitySHA256": "33d6cd5a5c3d01ea13cfdb132673a8353d3deadc9bb0eefa57c843140ef18968"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U4",
    "LessonID": "AMP-IM1-U4-I07",
    "LessonTitle": "Craft-a-Graph",
    "KeyOutcome": "I can use the key features of a function to build a graph of that function. | I can describe key features of a graph using terms like positive, negative, maximum, minimum, increasing, and decreasing.",
    "PlannedDays": 1,
    "NonParitySHA256": "b45767bb1432bdfb17907eee516156bd14d7e919c97f266ac8ce9b52bb423e3d"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U4",
    "LessonID": "AMP-IM1-U4-I08",
    "LessonTitle": "Plane, Train, and Automobile",
    "KeyOutcome": "I can calculate the average rate of change over an interval on a graph. | I can interpret the average rate of change in context.",
    "PlannedDays": 1,
    "NonParitySHA256": "71a0054062f439c114d66be16af2da3a8a9d5f46840844ec53483d2e3035c447"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U4",
    "LessonID": "AMP-IM1-U4-I09",
    "LessonTitle": "Space Race",
    "KeyOutcome": "I can interpret statements written in function notation and use them to compare key features of graphs. | I can compare and contrast key features of functions using statements written in function notation.",
    "PlannedDays": 1,
    "NonParitySHA256": "b3f091f3ec078d5a9df2bfc70a108eb1ae979efda6d0cdc20f2f6a58fa09ac70"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U4",
    "LessonID": "AMP-IM1-U4-I10",
    "LessonTitle": "Ins and Outs",
    "KeyOutcome": "I can determine if a value is a possible input or output for a function given in context. | I can describe the domain and range of a function as the set of all possible inputs and outputs.",
    "PlannedDays": 1,
    "NonParitySHA256": "c8cbc24f5703c6f8fe9c7b41d0b3dbeef9591192293efa092dc5324683f85a91"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U4",
    "LessonID": "AMP-IM1-U4-I11",
    "LessonTitle": "Elevator Stories",
    "KeyOutcome": "I can write the domain and range of a function using inequalities. | I can interpret the meaning of the domain and range in context.",
    "PlannedDays": 1,
    "NonParitySHA256": "084a191659300a7b12dc6272f057dcea3bda1292c2afe037133848aac74ef973"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U4",
    "LessonID": "AMP-IM1-U4-I12",
    "LessonTitle": "Marbleslides",
    "KeyOutcome": "I can restrict the domain and range of a function using inequalities. | I can explain how to restrict the domain and range of a function using inequalities.",
    "PlannedDays": 1,
    "NonParitySHA256": "f81f3e6593008606354b91bd131d87d8f7c75f2212866dbe06a450d3948fc005"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U4",
    "LessonID": "AMP-IM1-U4-I13",
    "LessonTitle": "M1.4 Practice Day 1",
    "KeyOutcome": "I can apply the concepts, skills, and strategies developed in Lessons 1–10.",
    "PlannedDays": 1,
    "NonParitySHA256": "d040448570a47cd076428b6043de50c44bd45e80897979b3210b328f165e0b58"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U4",
    "LessonID": "AMP-IM1-U4-I14",
    "LessonTitle": "M1.4 Sub-Unit Quiz",
    "KeyOutcome": "I can demonstrate my understanding of the concepts and skills developed so far in this unit.",
    "PlannedDays": 1,
    "NonParitySHA256": "dc207f78004b2e20a6fa3c9677bdfd56553781c6f1e6dc86409234b800a7b712"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U4",
    "LessonID": "AMP-IM1-U4-I15",
    "LessonTitle": "Recursion Excursion",
    "KeyOutcome": "I can write a recursive definition for a sequence using function notation. | I can describe how a sequence is a function with a domain that is a subset of the integers.",
    "PlannedDays": 1,
    "NonParitySHA256": "c18b28b5a56bdcb38a2d942f153fe11988d8898f088a6ed37f5826e606aa9f2a"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U4",
    "LessonID": "AMP-IM1-U4-I16",
    "LessonTitle": "Functions and Sequences",
    "KeyOutcome": "I can write recursive and explicit definitions for sequences using function notation. | I can compare and contrast the recursive definition and the explicit definition of a sequence written in function notation.",
    "PlannedDays": 1,
    "NonParitySHA256": "56454b41e1b2bf5b00d550f957f1a5a1cce56720184fe27c0579d262090c7111"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U4",
    "LessonID": "AMP-IM1-U4-I17",
    "LessonTitle": "What's Your Score?",
    "KeyOutcome": "I can evaluate and interpret outputs for absolute value functions. | I can describe how the absolute value function f(x).",
    "PlannedDays": 1,
    "NonParitySHA256": "7d5a32a9c608c6d42e719f9b886c479ab9349a4f8ca4adc90b229e47141d1617"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U4",
    "LessonID": "AMP-IM1-U4-I18",
    "LessonTitle": "Absolute Value Machines",
    "KeyOutcome": "I can graph an absolute value function. | I can analyze the key features (e.g., minimum, stretch or compression) of an absolute value function.",
    "PlannedDays": 1,
    "NonParitySHA256": "e3dcf3f71a4084a6e1e72528c0e196c3214fb5fb0fb597523dd2b6d187aa85d2"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U4",
    "LessonID": "AMP-IM1-U4-I19",
    "LessonTitle": "Our Math Stories",
    "KeyOutcome": "I can create graphs of functions that represent real-life relationships. | I can describe and interpret real-life relationships using function tools learned throughout this unit.",
    "PlannedDays": 1,
    "NonParitySHA256": "f500e447541e72ba26d23810e301d188e049c6ee01af602035fb7f54ae37cf9b"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U4",
    "LessonID": "AMP-IM1-U4-I20",
    "LessonTitle": "M1.4 Practice Day 2",
    "KeyOutcome": "I can apply the concepts, skills, and strategies developed in Lessons 1–15.",
    "PlannedDays": 1,
    "NonParitySHA256": "0927519a9942004ba372088cfadd82848fdba3425da32c3f11473c9f7d996feb"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U4",
    "LessonID": "AMP-IM1-U4-I21",
    "LessonTitle": "M1.4 Performance Task",
    "KeyOutcome": "I can demonstrate proficiency with the concepts and skills addressed in this unit.",
    "PlannedDays": 1,
    "NonParitySHA256": "5ec1f8830c804a730178617632b2cdcdb410fed660310351509d75a4e5109197"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U4",
    "LessonID": "AMP-IM1-U4-I22",
    "LessonTitle": "Unit Synthesis and Reflection",
    "KeyOutcome": "I can be purposeful, strategic, and goal-oriented about my learning. | I can connect different ideas from this unit and across units. | I can revisit ideas from this unit, revise my thinking, and reflect on my growth.",
    "PlannedDays": 1,
    "NonParitySHA256": "2de5f01f526ce070c54979c523fbca8977694b0bdb3f0ec5489b485e2cf54e69"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U5",
    "LessonID": "AMP-IM1-U5-I01",
    "LessonTitle": "M1.5 Pre-Unit Check",
    "KeyOutcome": "I can show what I already understand about ideas that will support this unit.",
    "PlannedDays": 1,
    "NonParitySHA256": "7adb230c90edd39719106c341986e69440d3a17f14e5f3069c929aa214e0f43d"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U5",
    "LessonID": "AMP-IM1-U5-I02",
    "LessonTitle": "An Epidemic",
    "KeyOutcome": "I can identify the growth pattern of an epidemic from a table. | I can recognize a graphical representation of an epidemic model. | I can describe the growth pattern of an epidemic.",
    "PlannedDays": 1,
    "NonParitySHA256": "25dcc6764a920cd3c9f590c31963e0dc64523a5a32f0ac91e44573c693207bc1"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U5",
    "LessonID": "AMP-IM1-U5-I03",
    "LessonTitle": "Carlos's Fish",
    "KeyOutcome": "I can use exponential equations to solve problems in context. | I can interpret the parameters of an exponential equation in context.",
    "PlannedDays": 1,
    "NonParitySHA256": "031c7c6d5e03d80a09222080728b934bd0386bbcdb074b2e40887ab36248194b"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U5",
    "LessonID": "AMP-IM1-U5-I04",
    "LessonTitle": "Growing Globs",
    "KeyOutcome": "I can identify functions that grow by constant differences as linear functions and functions that grow by constant ratios as exponential functions. | I can compare linear and exponential functions by their key features. | I can explain that quantities that grow exponentially eventually exceed quantities that grow linearly.",
    "PlannedDays": 1,
    "NonParitySHA256": "88975caf836677b218ffd5ccb1f87f3422debddabd6b53ce09f50f0f584713f8"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U5",
    "LessonID": "AMP-IM1-U5-I05",
    "LessonTitle": "Going Viral",
    "KeyOutcome": "I can write exponential functions to represent graphs or situations. | I can compare and contrast graphs of exponential and linear function in context.",
    "PlannedDays": 1,
    "NonParitySHA256": "3a23d70046f5c1f0dddeb6c3f8424f8cee778517209f8abda3d771b733080198"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U5",
    "LessonID": "AMP-IM1-U5-I06",
    "LessonTitle": "Return of the Globs",
    "KeyOutcome": "I can create functions, tables, and graphs of linear and exponential relationships. | I can describe connections between functions, tables, graphs, and situations that represent an exponential or linear relationship.",
    "PlannedDays": 1,
    "NonParitySHA256": "a55a33af9f0ab315d05c2be5653fed3cc485b1a0fb7a8bc32e082b6e8e6863db"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U5",
    "LessonID": "AMP-IM1-U5-I07",
    "LessonTitle": "Carlos and Corals",
    "KeyOutcome": "I can evaluate exponential functions with positive, zero, and negative inputs. | I can describe the domain of an exponential function in context.",
    "PlannedDays": 1,
    "NonParitySHA256": "12e884142b90b7f9c607428ea64fcd57e755a75ee74ad3dc0490ca7443563f85"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U5",
    "LessonID": "AMP-IM1-U5-I08",
    "LessonTitle": "Differences and Factors",
    "KeyOutcome": "I can prove that linear functions grow by equal differences over equal intervals and that exponential functions grow by equal factors over equal intervals. | I can explain how exponential functions change by a factor and linear functions change by a difference.",
    "PlannedDays": 1,
    "NonParitySHA256": "a3e1190f7b6b6e05b31c5adb3eb78d549c22e83050846275c0a3a17257b12618"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U5",
    "LessonID": "AMP-IM1-U5-I09",
    "LessonTitle": "Growing Mold",
    "KeyOutcome": "I can model repeated percent increase with exponential functions. | I can interpret the initial value and growth factor of an exponential function representing percent increase.",
    "PlannedDays": 1,
    "NonParitySHA256": "04f2d661da2379a8924ad274b1ca2fea454ebc90a71f58456a0a73124302b216"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U5",
    "LessonID": "AMP-IM1-U5-I10",
    "LessonTitle": "At a Loss",
    "KeyOutcome": "I can calculate percent change of exponential functions from a graph. | I can write equivalent functions that represent exponential decay. | I can compare and contrast equivalent equations of functions that represent exponential decay.",
    "PlannedDays": 1,
    "NonParitySHA256": "4714965855911d21a9ccafcc3381ba2719589b292cd88399679ee1d17dbafb73"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U5",
    "LessonID": "AMP-IM1-U5-I11",
    "LessonTitle": "Lake Desmosia",
    "KeyOutcome": "I can use exponential functions to solve problems in context. | I can interpret the parameters of exponential functions in context.",
    "PlannedDays": 1,
    "NonParitySHA256": "727bc2e7939b759da845b970a48f27500466e6c1bfaacfc4dec68d70ad4b18d1"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U5",
    "LessonID": "AMP-IM1-U5-I12",
    "LessonTitle": "Marbleslides: Exponentials",
    "KeyOutcome": "I can write exponential functions that meet specified criteria. | I can describe the effect of vertical and horizontal translations on the graph of an exponential function.",
    "PlannedDays": 1,
    "NonParitySHA256": "0ad1fa3e632d4d32b61a0645036f5d6c29ac2e62aa3556990ddff20d4c4d61a9"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U5",
    "LessonID": "AMP-IM1-U5-I13",
    "LessonTitle": "M1.5 Practice Day 1",
    "KeyOutcome": "I can apply the concepts, skills, and strategies developed in Lessons 1–10.",
    "PlannedDays": 1,
    "NonParitySHA256": "eb36f9583163cf177c9007055dfb6863128bb03d730210ce4feb111d991e04da"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U5",
    "LessonID": "AMP-IM1-U5-I14",
    "LessonTitle": "M1.5 Sub-Unit Quiz",
    "KeyOutcome": "I can demonstrate my understanding of the concepts and skills developed so far in this unit.",
    "PlannedDays": 1,
    "NonParitySHA256": "beed6e32e058f2b9b1939c6a5e287126b7d07aa23f1c8dda3f05360d2be4a79b"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U5",
    "LessonID": "AMP-IM1-U5-I15",
    "LessonTitle": "Bank Accounts",
    "KeyOutcome": "I can use a graphing calculator to solve problems involving linear and exponential functions. | I can describe connections between simple and compound interest, and linear and exponential functions.",
    "PlannedDays": 1,
    "NonParitySHA256": "7f10ca99b65e4e56f515d44ea46c26110d2d6399c77d87e84c2fa6f0207309b4"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U5",
    "LessonID": "AMP-IM1-U5-I16",
    "LessonTitle": "Payday Loan",
    "KeyOutcome": "I can write exponential functions that represent situations involving compound interest. | I can interpret parts of an exponential expression in context.",
    "PlannedDays": 1,
    "NonParitySHA256": "78b94b9f83054c3df6210e3542a55915126ac9f700f4d9f581077ce1ad47825a"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U5",
    "LessonID": "AMP-IM1-U5-I17",
    "LessonTitle": "Credit Card Compounding",
    "KeyOutcome": "I can calculate account balances given an initial amount, annual interest rate, compounding interval, and period of time. | I can interpret parts of exponential expressions that represent annual interest rates with different compounding intervals i (semi-annually, quarterly, monthly).",
    "PlannedDays": 1,
    "NonParitySHA256": "0e278edc5d1ec573fda4c1b35215d129cdcb050bcd2c4ee13d46df3d734bd638"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U5",
    "LessonID": "AMP-IM1-U5-I18",
    "LessonTitle": "Detroit's Population, Part 1",
    "KeyOutcome": "I can fit an exponential or linear function to data. | I can use linear and exponential models to make predictions. | I can interpret the parameters of linear and exponential models in context.",
    "PlannedDays": 1,
    "NonParitySHA256": "3142482ab4c3d0fc2f38dddd6f028560e640e7983f56ddd0b3b9f1f10ad24da6"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U5",
    "LessonID": "AMP-IM1-U5-I19",
    "LessonTitle": "Detroit's Population, Part 2",
    "KeyOutcome": "I can use a graphing calculator to create a linear or exponential model that fits data. | I can informally assess how well a function fits data. | I can critique the usefulness of a model based on the limitations of its context.",
    "PlannedDays": 1,
    "NonParitySHA256": "544b53e90145f84a07cfbbe3de609de7292c5096629c0cbcabc890a7e61faa8b"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U5",
    "LessonID": "AMP-IM1-U5-I20",
    "LessonTitle": "M1.5 Practice Day 2",
    "KeyOutcome": "I can apply the concepts, skills, and strategies developed in Lessons 1–15.",
    "PlannedDays": 1,
    "NonParitySHA256": "4122d850b41f5def6c1c4ff96f7746a29a7f93c486add7c4909b6396c05a21eb"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U5",
    "LessonID": "AMP-IM1-U5-I21",
    "LessonTitle": "M1.5 Performance Task",
    "KeyOutcome": "I can demonstrate proficiency with the concepts and skills addressed in this unit.",
    "PlannedDays": 1,
    "NonParitySHA256": "c98bb226ab47c3d27d85458ec4ce6d443c1224c50738c6b4cfdda391eac19997"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U5",
    "LessonID": "AMP-IM1-U5-I22",
    "LessonTitle": "Unit Synthesis and Reflection",
    "KeyOutcome": "I can be purposeful, strategic, and goal-oriented about my learning. | I can connect different ideas from this unit and across units. | I can revisit ideas from this unit, revise my thinking, and reflect on my growth.",
    "PlannedDays": 1,
    "NonParitySHA256": "c7ff1f22555e8d6522e2d69ee02b9c99ebdef9692f7f19eb52e42ecc71074df8"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U5",
    "LessonID": "AMP-IM1-U5-F1",
    "LessonTitle": "Tuition Costs",
    "KeyOutcome": "I can investigate trends in post-secondary tuition costs.",
    "PlannedDays": 1,
    "NonParitySHA256": "bad24d10c6ef200525cb8570214e28288e194697f70b8788adcb0b206d42ca02"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I01",
    "LessonTitle": "M1.6 Pre-Unit Check",
    "KeyOutcome": "I can show what I already understand about ideas that will support this unit.",
    "PlannedDays": 1,
    "NonParitySHA256": "805d075c395e16e13d1cffcdd7626e0b9424355a8247971a2ea7f8f4484a9e75"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I02",
    "LessonTitle": "Making Precise Symbols",
    "KeyOutcome": "I can draw symbols and geometric shapes or concepts with precision. | I can describe what it means for a geometric drawing to be precise.",
    "PlannedDays": 1,
    "NonParitySHA256": "fb63ae0cf6448d3048e048093f9f3183b9f5358c242a9bd3e7dd93b011bc6820"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I03",
    "LessonTitle": "Circles and Segments",
    "KeyOutcome": "I can use a circle to construct different segments of the same length. | I can explain how circles help to construct figures with equal side lengths.",
    "PlannedDays": 1,
    "NonParitySHA256": "914dab307a6207ca552e7a7f8aa4daa125576592b134c0167da4788c6676e0b5"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I04",
    "LessonTitle": "Compass Constructions",
    "KeyOutcome": "I can use a compass and straightedge to construct equilateral triangles and regular hexagons. | I can describe processes for performing compass and straightedge constructions.",
    "PlannedDays": 1,
    "NonParitySHA256": "dcdf13d8bca4574794ef50fa45d4ffb176e5b4bdb32a5e043dafb74d1f0e3868"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I05",
    "LessonTitle": "Constructing Digitally",
    "KeyOutcome": "I can use digital construction tools to construct geometric objects. | I can write and follow precise instructions to create geometric objects.",
    "PlannedDays": 1,
    "NonParitySHA256": "31e69875fb030fb5ecbc8950684ec4bf403a70f8daa1f92881e35a18bfa98738"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I06",
    "LessonTitle": "Right in the Middle",
    "KeyOutcome": "I can construct the perpendicular bisector of a line segment. | I can describe that points that are equidistant from a line segment’s endpoints will be on the perpendicular bisector of that U segment.",
    "PlannedDays": 1,
    "NonParitySHA256": "a9ce9fc55a2a93b6d793bc527ca96139b6eac141eacedb97f90780eb70380722"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I07",
    "LessonTitle": "Lines of Construction",
    "KeyOutcome": "I can construct perpendicular and parallel lines that pass through given points. | I can write precise instructions for completing a construction.",
    "PlannedDays": 1,
    "NonParitySHA256": "f653adab73b66fd1d629c3dbb078a889ebeb4c172147ec4636fa6aadde2f4e67"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I08",
    "LessonTitle": "Square Up",
    "KeyOutcome": "I can construct a square and a square inscribed in a circle. | I can describe how construction techniques such as finding a midpoint or constructing a perpendicular line are used to construct a square.",
    "PlannedDays": 1,
    "NonParitySHA256": "02ad9e41000607aaec54454c54b07bbc1011cc0bc24aa4c59b29e4228f666da7"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I09",
    "LessonTitle": "Community Constructions",
    "KeyOutcome": "I can construct perpendicular bisectors to create regions closest to a certain location. | I can explain how perpendicular bisectors and Voronoi diagrams can help us make sense of where to put community resources.",
    "PlannedDays": 1,
    "NonParitySHA256": "53957c6855ac505f0993b1b63c9b3d011cce57f662659ad642688128c713982e"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I10",
    "LessonTitle": "M1.6 Practice Day 1",
    "KeyOutcome": "I can apply the concepts, skills, and strategies developed in Lessons 1–7.",
    "PlannedDays": 1,
    "NonParitySHA256": "e5312d958d7b6fc9477022be6bac9c1ee9e95f073ddfd1fa0a4e7a8633599339"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I11",
    "LessonTitle": "Going Off the Grid, Part 1",
    "KeyOutcome": "I can design a sequence of rigid transformations that takes a figure onto another. | I can write and follow instructions to perform a sequence of transformations.",
    "PlannedDays": 1,
    "NonParitySHA256": "bc6c96fec7a42e7ed005aec80bba301f77f4fc2747fe6512a2181ab533081733"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I12",
    "LessonTitle": "Time to Reflect",
    "KeyOutcome": "I can reflect figures precisely using a variety of tools. | I can describe what happens to a pre-image when it is reflected over a given line.",
    "PlannedDays": 1,
    "NonParitySHA256": "6cb5757f325a536783fa79bc25c5009bb29194afc64f3c58882a0a3d9b91ce8b"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I13",
    "LessonTitle": "Translation Information",
    "KeyOutcome": "I can translate figures precisely using a variety of tools. | I can describe and interpret translations and reflections precisely.",
    "PlannedDays": 1,
    "NonParitySHA256": "ee5bf13e05dccdca52368b7836eecb10afbb15dc83020a9b834b5bf58fafe9be"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I14",
    "LessonTitle": "Rotation Devices",
    "KeyOutcome": "I can rotate figures precisely using a variety of tools. | I can describe rotations using a center of rotation, direction of rotation, and angle of rotation.",
    "PlannedDays": 1,
    "NonParitySHA256": "1c26d3078e1fa8d82adacdf340666e63ba62539aa83ea1758180949152aa4de9"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I15",
    "LessonTitle": "Going Off the Grid, Part 2",
    "KeyOutcome": "I can use geometry tools to perform a sequence of rigid transformations that moves a figure onto another. | I can describe a sequence of rigid transformations that moves one figure onto another using mathematically precise language.",
    "PlannedDays": 1,
    "NonParitySHA256": "d5646825fc3d83e439f8e8fd1b978afbb6d970444211342678a401c1c06c9b06"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I16",
    "LessonTitle": "Tiles and Patterns",
    "KeyOutcome": "I can use an underlying construction to create polygons that can be transformed into geometric patterns. | I can describe connections between geometric patterns from Islamic cultures, constructions, and transformations.",
    "PlannedDays": 1,
    "NonParitySHA256": "2d53b201cfbab66b26e05d2bb5d9d9725604f3683d10e7837cc8f2853736c6aa"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I17",
    "LessonTitle": "Reflectional Symmetry",
    "KeyOutcome": "I can determine whether a figure has reflectional symmetry. | I can determine the lines of symmetry for a figure. | I can describe the reflections that take a figure onto itself.",
    "PlannedDays": 1,
    "NonParitySHA256": "aaa2c2f28e8b8aa54a56ba054e07bf4091eeb706fcc76dc116b7eb82dfa97a96"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I18",
    "LessonTitle": "Rotational Symmetry",
    "KeyOutcome": "I can determine whether a figure has rotational symmetry. | I can sketch rotations that create symmetry. | I can describe rotations that take a figure onto itself.",
    "PlannedDays": 1,
    "NonParitySHA256": "c2182def95ce6672148ed4c03af11abda5a53fabb1b1024b15f57b73ab4ff256"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I19",
    "LessonTitle": "Transformations as Functions",
    "KeyOutcome": "I can use coordinate transformation notation as a function to take points in the plane as inputs and give transformed points as outputs. | I can precisely define a transformation when given in coordinate transformation notation.",
    "PlannedDays": 1,
    "NonParitySHA256": "9cc826562c5f02b1e5c1d7928648e4a890a0176901a9202f2a7e23f69b6d7b60"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I20",
    "LessonTitle": "M1.6 Practice Day 2",
    "KeyOutcome": "I can apply the concepts, skills, and strategies developed in Lessons 1–16.",
    "PlannedDays": 1,
    "NonParitySHA256": "745c8dbeed680573ffa7fde6c5f0cc74f9da0913200c02d5231cbd0deb4fc790"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I21",
    "LessonTitle": "M1.6 Sub-Unit Quiz",
    "KeyOutcome": "I can demonstrate my understanding of the concepts and skills developed so far in this unit.",
    "PlannedDays": 1,
    "NonParitySHA256": "39a0ba4f97e6cc69eb9822e2d3263a68bfcbae2f82ce1577f476c2e4aa16f699"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I22",
    "LessonTitle": "Congruent Parts, Part 1",
    "KeyOutcome": "I can identify corresponding parts in diagrams. | I can explain why figures and corresponding parts are congruent using rigid transformations.",
    "PlannedDays": 1,
    "NonParitySHA256": "07200da25ba660ec12f200cd65525b731147de78cc45b290713fda86f1edf502"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I23",
    "LessonTitle": "Congruent Parts, Part 2",
    "KeyOutcome": "I can identify corresponding parts from a congruence statement. | I can write a congruence statement using words or geometric symbols.",
    "PlannedDays": 1,
    "NonParitySHA256": "c63b1b141084a51f2b63785198d55494162c1b04fdf0a3836019a50219041877"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I24",
    "LessonTitle": "Congruent Triangles, Part 1",
    "KeyOutcome": "I can show congruence of two triangles whose corresponding parts are congruent by determining and performing rigid. | I can describe why parts of two congruent triangles coincide using properties of rigid transformations.",
    "PlannedDays": 1,
    "NonParitySHA256": "648d4e4f964d77377b1b935514634b88aaf3f9a1385dab8237509c486bb63d8a"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I25",
    "LessonTitle": "Congruent Triangles, Part 2",
    "KeyOutcome": "I can create congruent triangles given angle measures and/or side lengths. | I can determine and request the specific information needed to create congruent triangles.",
    "PlannedDays": 1,
    "NonParitySHA256": "1788a44338a03b2bebe7efe6f4f57cf3648686dd7c6269d2323dad69f65ff228"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I26",
    "LessonTitle": "Triangle Palindromes",
    "KeyOutcome": "I can use rigid transformations to show SAS and ASA triangle congruence theorems are true. | I can use SAS or ASA triangle congruence to explain why two triangles are congruent.",
    "PlannedDays": 1,
    "NonParitySHA256": "a57fb4cf9270e73c79ae79a5920e5dca5f088de5b6f38f2f466d0c59e4aaf083"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I27",
    "LessonTitle": "Another Triangle Congruence Theorem",
    "KeyOutcome": "I can determine if two triangles are congruent by SAS, ASA, or SSS congruence. | I can use rigid transformations to explain SSS triangle congruence.",
    "PlannedDays": 1,
    "NonParitySHA256": "0ba9a80fdc290588d4998a4d8b424bcb8addaf348dfd9c1bbbd80f3ac24fa148"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I28",
    "LessonTitle": "M1.6 Practice Day 3",
    "KeyOutcome": "I can apply the concepts, skills, and strategies developed in Lessons 1–22.",
    "PlannedDays": 1,
    "NonParitySHA256": "dc460664d280d45d74701568b3d0cb66bbee15d70115be0180a0758dd39f0e98"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I29",
    "LessonTitle": "M1.6 Performance Task",
    "KeyOutcome": "I can demonstrate proficiency with the concepts and skills addressed in this unit.",
    "PlannedDays": 1,
    "NonParitySHA256": "09f5154789e74f3b0ea5b82bdc75395b32e791027dc4e1b48af467e867cbe5c6"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U6",
    "LessonID": "AMP-IM1-U6-I30",
    "LessonTitle": "Unit Synthesis and Reflection",
    "KeyOutcome": "I can be purposeful, strategic, and goal-oriented about my learning. | I can connect different ideas from this unit and across units. | I can revisit ideas from this unit, revise my thinking, and reflect on my growth.",
    "PlannedDays": 1,
    "NonParitySHA256": "ef64e9d1f199a1ada57eaf49b1c0df1414dd2dac6d171def7d08eca0a78c12d6"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I01",
    "LessonTitle": "M1.7 Pre-Unit Check",
    "KeyOutcome": "I can show what I already understand about ideas that will support this unit.",
    "PlannedDays": 1,
    "NonParitySHA256": "22122fb8a40c640ba2bf7375344892ff6b3cda9acfeb4425695e12de16f830eb"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I02",
    "LessonTitle": "A Statistical Question",
    "KeyOutcome": "I can describe the features of data representations that are important to examine when making conclusions about data sets. | I can describe the difference between statistical and non-statistical questions.",
    "PlannedDays": 1,
    "NonParitySHA256": "b2ca43f20b7e7dccbbad43e1b1c94be0266480020bdbeac35ccda8ea54a03f8b"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I03",
    "LessonTitle": "Survey Says",
    "KeyOutcome": "I can explain the difference between quantitative and categorical data.",
    "PlannedDays": 1,
    "NonParitySHA256": "8881455c56b1260825c3c8235d79b1a56399d2b17f9d00ee134eeaef07e026e5"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I04",
    "LessonTitle": "Hear Here",
    "KeyOutcome": "I can represent categorical data in two-way frequency tables and conditional relative frequency tables. | I can calculate values in two-way frequency tables and conditional relative frequency tables. | I can analyze two-way frequency tables for associations in data.",
    "PlannedDays": 1,
    "NonParitySHA256": "359b8854838db6481e08a39e9159c056d38bd8b1c06ee4fdc1b12b7b2f910597"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I05",
    "LessonTitle": "School Choice",
    "KeyOutcome": "I can calculate values in total relative frequency tables by row, column, or total. | I can create total relative frequency tables and two-way frequency tables. | I can analyze relative frequency tables to determine if there is an association between two variables.",
    "PlannedDays": 1,
    "NonParitySHA256": "61e8c80b6b0ed10c1f6526ce873b532178a11e51c6c5c6443340de77e9ed9068"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I06",
    "LessonTitle": "Love it or Leave it",
    "KeyOutcome": "I can use technology to represent data with a dot plot or histogram. | I can describe the advantages of using a dot plot or a histogram to represent data.",
    "PlannedDays": 1,
    "NonParitySHA256": "9384591a84062ac094d8b9081fe15015b0966bee7c48d0834c4a698f2071cd9e"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I07",
    "LessonTitle": "Better Weather?",
    "KeyOutcome": "I can use technology to construct box plots. | I can compare and contrast two data sets represented by box plots. | I can interpret the parts of box plots that represent real-world data.",
    "PlannedDays": 1,
    "NonParitySHA256": "9171b444a62d0e89e6a67c2f3d7dc5f934e258abd0a8557beb94d236c3d2be17"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I08",
    "LessonTitle": "Shapes of Data",
    "KeyOutcome": "I can describe the shape of a data set using terms like bimodal, bell-shaped, skewed, symmetric, and uniform.",
    "PlannedDays": 1,
    "NonParitySHA256": "62347eb1c3b65006346049adf7db1f4f7249280aab4bdce9cdd65fb304170cd2"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I09",
    "LessonTitle": "Quick Pick",
    "KeyOutcome": "I can use technology to calculate the measures of center (mean and median) for a data set. | I can explain how to calculate the mean and median, and what these tell us about a data set. | I can explain the effect of extreme values on the mean and median.",
    "PlannedDays": 1,
    "NonParitySHA256": "f7bb0d94f8d44263c5abf1d7048d4a7e2ea864e0d6478ef2bb8ebca015226be1"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I10",
    "LessonTitle": "Finding Desmo",
    "KeyOutcome": "I can explain that standard deviation is a measure of spread and use technology to calculate the standard deviation for a data set. | I can compare and contrast data sets using standard deviation.",
    "PlannedDays": 1,
    "NonParitySHA256": "1bf2f2d774a1f6459d5a1eb1a29ec0ec1864d7d7dbc65cd0eea3a42a045cc970"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I11",
    "LessonTitle": "Wavering Weather",
    "KeyOutcome": "I can compare and contrast two data sets using the mean and standard deviation.",
    "PlannedDays": 1,
    "NonParitySHA256": "479dba4ddf860243c0bda11775b687989de905fed6d846e2fb0064bc6f5f2196"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I12",
    "LessonTitle": "Race Car",
    "KeyOutcome": "I can explain that the interquartile range (IQR) is a measure of spread and calculate the IQR for a data set. | I can compare and contrast skewed data sets using the median and IQR.",
    "PlannedDays": 1,
    "NonParitySHA256": "06deac3a5a903e97a214d61a59e216226af68003261cd90d04f12fd4f069db67"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I13",
    "LessonTitle": "Far Out",
    "KeyOutcome": "I can determine whether or not a data point is an outlier. | I can explain how outliers impact the mean or median of a data set.",
    "PlannedDays": 1,
    "NonParitySHA256": "5cc81abde13384e8189f7ae3cf226b264350cf0cd6f11cfb9c9bb2bcc123aa4a"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I14",
    "LessonTitle": "Dynamic Decades",
    "KeyOutcome": "I can compare and contrast two data sets using measures of center and spread that are appropriate for the shape of the data.",
    "PlannedDays": 1,
    "NonParitySHA256": "b02f3ae73da226db76f289075958e5d615c919e1d9f57373e8f2be04ae50ae76"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I15",
    "LessonTitle": "M1.7 Practice Day 1",
    "KeyOutcome": "I can apply the concepts, skills, and strategies developed in Lessons 1–12.",
    "PlannedDays": 1,
    "NonParitySHA256": "fd207043f402565cb4f58a14faae81ca8810f795fef53850118f66ba12a8a471"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I16",
    "LessonTitle": "M1.7 Sub-Unit Quiz",
    "KeyOutcome": "I can demonstrate my understanding of the concepts and skills developed so far in this unit.",
    "PlannedDays": 1,
    "NonParitySHA256": "7e2c4f531e48d40d6d498ea03b223f38e9d7f625a472d0c43e39d81bddf6e321"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I17",
    "LessonTitle": "Correlation Coefficient",
    "KeyOutcome": "I can use technology to calculate the correlation coefficient of data on a scatter plot. | I can describe the strength and direction of a linear association between two variables on a scatter plot using the correlation coefficient.",
    "PlannedDays": 1,
    "NonParitySHA256": "b4c1807ce728c4322f96281d0f1ea49a055f37042f4e0ec0a2cf0840b582566c"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I18",
    "LessonTitle": "How Hot Is It?",
    "KeyOutcome": "I can use the correlation coefficient to describe the strength and direction of a linear association. | I can interpret a correlation coefficient in context.",
    "PlannedDays": 1,
    "NonParitySHA256": "971e0271cc9e4d45538eae3656ff491ff1ddf6a752b963aea2c5b28eee5d4e99"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I19",
    "LessonTitle": "City Slopes",
    "KeyOutcome": "I can estimate unknown values using a linear model for data on a scatter plot. | I can interpret the slope and y-intercept for a linear model in context.",
    "PlannedDays": 1,
    "NonParitySHA256": "d21eb9863d2cd6e364dfc208e4f45f255254003b09af1778e2dae0f3c5f642f4"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I20",
    "LessonTitle": "Residual Fruit",
    "KeyOutcome": "I can make connections between residual plots and residuals on a graph. | I can use residuals and residual plots to understand what it means for a line to fit data well. | I can identify when a residual plot indicates a better or worse fit.",
    "PlannedDays": 1,
    "NonParitySHA256": "ce0c22a8a2670c294d9fadfa8246b407c3b2ae55063eb1c339b0dd09e6a6a1ba"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I21",
    "LessonTitle": "Penguin Populations",
    "KeyOutcome": "I can use technology to generate the line of best fit for data on a scatter plot. | I can use the equation of a line of best fit to make predictions. | I can interpret the slope and y-intercept of the equation of a line of best fit in context.",
    "PlannedDays": 1,
    "NonParitySHA256": "5abcd4734a3e44d91a3100bdbba1bb97625c0f265896b0a4aff9abe600fae87d"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I22",
    "LessonTitle": "Behind the Headlines",
    "KeyOutcome": "I can determine if the relationship between two variables represents correlation or causation. | I can analyze claims to determine if there is enough information to support causation.",
    "PlannedDays": 1,
    "NonParitySHA256": "814cf10ec4e779d895850a4f8b050bf554b9e40770ce2013988d4c5b723390c1"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I23",
    "LessonTitle": "City Data",
    "KeyOutcome": "I can use statistical tools to explore relationships in real-world data. | I can analyze the relationship between two variables in context using scatter plots, lines of best fit, and correlation coefficients.",
    "PlannedDays": 1,
    "NonParitySHA256": "ecbf737932bf94d107f93e18fc3174e4477360cd6c679fe5f91113affbb1dae7"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I24",
    "LessonTitle": "M1.7 Practice Day 2",
    "KeyOutcome": "I can apply the concepts, skills, and strategies developed in Lessons 1–19.",
    "PlannedDays": 1,
    "NonParitySHA256": "2585eedbf028f034510dede98eec7c2b75cc32bc18bdb4cc20d9d5e7011889dd"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I25",
    "LessonTitle": "M1.7 Performance Task",
    "KeyOutcome": "I can demonstrate proficiency with the concepts and skills addressed in this unit.",
    "PlannedDays": 1,
    "NonParitySHA256": "54e8ef289d3a1cce5004ef4bc0c574a23424ae684d1e06fec531b0cb1db9072b"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-I26",
    "LessonTitle": "Unit Synthesis and Reflection",
    "KeyOutcome": "I can be purposeful, strategic, and goal-oriented about my learning. | I can connect different ideas from this unit and across units. | I can revisit ideas from this unit, revise my thinking, and reflect on my growth.",
    "PlannedDays": 1,
    "NonParitySHA256": "9c8f30481d043529259bf170e1c593d5bf4ded2d74b199109f6cb43b2a92e21b"
  },
  {
    "CourseID": "IM1",
    "UnitID": "AMP-IM1-U7",
    "LessonID": "AMP-IM1-U7-F1",
    "LessonTitle": "Exploring Climate Change",
    "KeyOutcome": "I can investigate climate change and identify actions that could reduce my carbon footprint.",
    "PlannedDays": 1,
    "NonParitySHA256": "e2b9e21b279a79c60afb6a4387413a1606da76e33194981c300c9767c00b4c4d"
  }
];
